# This workflow will do a clean install of node dependencies, build the source code and push the binaries to the deployment repository.
name: Continuous Delivery and Deployment

on:
  pull_request:
    types:
      - labeled

jobs:
    build:
        if: contains(github.event.pull_request.labels.*.name, 'pr-deploy')
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build-hash
            - name: Create CNAME file
              uses: finnp/create-file-action@master
              env:
                  FILE_NAME: build/hash-history/CNAME
                  FILE_DATA: pr.bts.mobi
            - name: Deploy
              uses: s0/git-publish-subdir-action@master
              env:
                  REPO: git@github.com:abitmore/pr.bts.mobi.git
                  BRANCH: master
                  FOLDER: build/hash-history
                  SSH_PRIVATE_KEY: ${{ secrets.AUTOMATION_UI_DEPLOYMENT_KEY }}
